<a href="https://colab.research.google.com/github/mayurraj9378/Data-Science/blob/main/numpy_part3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
# astype() --> used to change the data type of an array into another data type

arr = np.array([10,20,30])
print(arr.dtype)

arr = arr.astype('f')  # float64bits   f32bits
print(arr.dtype)
print(arr)

int64
float32
[10. 20. 30.]


In [ ]:
arr = np.array([10.2,20.3,30.4],dtype='i')
print(arr.dtype)
print(arr)

int32
[10 20 30]


In [ ]:
# copy()  and  view()
# in copy() if you make any changes in original array , it won't effect copied array
# and if you make any changes in copied array , it won't effect original array

org_arr = np.array([10,20,30,40,50,60])
copied_arr = org_arr.copy()

print(org_arr)
print(copied_arr)

copied_arr[1] = 200
print('Original Array : ',org_arr)
print('Copied Array : ',copied_arr)

[10 20 30 40 50 60]
[10 20 30 40 50 60]
Original Array :  [10 20 30 40 50 60]
Copied Array :  [ 10 200  30  40  50  60]


In [ ]:
# in view() if you make any changes in original array , it will effect copied array
# and if you make any changes in copied array , it will effect original array

org_arr = np.array([10,20,30,40,50,60])
copied_arr = org_arr.view()

print(org_arr)
print(copied_arr)

copied_arr[1] = 200
print('Original Array : ',org_arr)
print('Copied Array : ',copied_arr)

[10 20 30 40 50 60]
[10 20 30 40 50 60]
Original Array :  [ 10 200  30  40  50  60]
Copied Array :  [ 10 200  30  40  50  60]


In [ ]:
# reshape()
# used to change the dimensions of an array

# convert 1D into 2D

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr.shape)   # 12 -->  2X6  6X2  3X4  4X3  12X1  1X12

arr = arr.reshape(2,6)
print(arr)
print(arr.shape)

(12,)
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(2, 6)


In [ ]:
# reshape()
# used to change the dimensions of an array

# convert 1D into 2D

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr.shape)   # 12 -->  2X6  6X2  3X4  4X3  12X1  1X12

arr = arr.reshape(2,6)
print(arr)
print(arr.shape)

(12,)
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(2, 6)


In [ ]:
# convert 2D into 1D
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.shape)

arr = arr.reshape(6)
print(arr)
print(arr.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[1 2 3 4 5 6]
(6,)


In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
arr = arr.reshape(-1)
print(arr)
print(arr.shape)

[1 2 3 4 5 6]
(6,)


In [ ]:
# Filter an array
arr = np.array([1,4,2,7,8,3,9,10,2,4])
res = arr > 5
print(res)  # BOOLEAN MASKING
print(arr[res])

[False False False  True  True False  True  True False False]
[ 7  8  9 10]


In [ ]:
arr = np.array([1,4,2,7,8,3,9,10,2,4])
res = arr%2==0
print(res)  # BOOLEAN MASKING
print(arr[res])

[False  True  True False  True False False  True  True  True]
[ 4  2  8 10  2  4]


In [ ]:
arr = np.array([1,4,2,7,8,3,9,10,2,4])
res = (arr > 4) & (arr < 9)
print(arr[res])

[7 8]


In [ ]:
# Modify Elements Using Boolean Indexing
arr = np.array([10,12,15,18,19,21,25,32,35,36])
print(arr)
copied_arr = arr.copy()
copied_arr[arr%2==0] = 0
print(copied_arr)

[10 12 15 18 19 21 25 32 35 36]
[ 0  0 15  0 19 21 25  0 35  0]
