<a href="https://colab.research.google.com/github/mayurraj9378/Data-Science/blob/main/numpy_part2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# numpy array()
arr = np.array([10,20,30,40,50,60])
print(arr)

[10 20 30 40 50 60]


In [ ]:
# shape property
# used to determine the dimensions of an array

# for 1D array shape returns (n,)
# where n is the number of elements

# for 2D array shape returns (n,m)
# where n is the number of rows and m is the number of columns

print(arr.shape)

(6,)


In [ ]:
# Indexing and Slicing
print(arr)

# 10 20 30 40 50 60
# 0   1  2  3  4  5
# -6  -5 -4 -3 -2 -1

print(arr[2])
print(arr[-1])

print(arr[1:5])

# wap to print array elements in a reverse order
print(arr[::-1])

[10 20 30 40 50 60]
30
60
[20 30 40 50]
[60 50 40 30 20 10]


In [ ]:
# 2D Array
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr.shape)

arr = np.array([[1,2],[3,4],[5,6],[7,8]])
print(arr.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
(4, 2)


In [ ]:
# indexing in 2D Array
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr.shape)

print(arr[0,2])

# print the second row
print(arr[1,:])

# print the third column
print(arr[:,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
3
[4 5 6]
[3 6 9]


In [ ]:
# dtype property : used to determine the data type of an array
arr = np.array([10,20,30,40,50])
print(arr.dtype)

arr = np.array([10,20,30,40,50],dtype='i2')
print(arr.dtype)

arr = np.array([10,20,30,40,50],dtype='i1')
print(arr.dtype)

int64
int16
int8
