<a href="https://colab.research.google.com/github/mayurraj9378/Data-Science/blob/main/numpy_part5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
#full (size , constantValue )
#used to create an array with a constant value
x=np.full(9,24)
print (x)

[24 24 24 24 24 24 24 24 24]


In [ ]:
x=np.full((3,4),24)
print (x)

[[24 24 24 24]
 [24 24 24 24]
 [24 24 24 24]]


In [ ]:
#arange
#it is used to create an array filled with sequence of integer values
#arange(x)
#it is used to create an array filled with sequence of integer values
#starting from zero till x-1
print (np.arange(11))

[ 0  1  2  3  4  5  6  7  8  9 10]


In [ ]:
#arange(x,y)
#starting from x till y-1
print (np.arange(56,200))

[ 56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73
  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91
  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108 109
 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127
 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145
 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163
 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181
 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199]


In [ ]:
#arange(x,y,stepCount)
#starting from x till y-1 based on stepcount
print (np.arange(1,21))
print (np.arange (1,21,4))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 1  5  9 13 17]


In [ ]:
#sum
x=np.arange(1,21)
print(x)
print(np.sum(x))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
210


In [ ]:
#Numpy Random Module
from numpy import random
#randint()
x=random.randint(20)
print(x)

5


In [ ]:
x=random.randint(20,50)
print(x)

36


In [ ]:
#1d array using random
arr = random.randint(100,size=(5))
print(arr)

[ 0 74 90 47  9]


In [ ]:
#2d array using random
arr = random.randint(50,100,size=(4,5))
print (arr)

[[74 65 81 50 53]
 [51 68 80 93 80]
 [75 52 56 59 94]
 [80 90 83 82 77]]


In [ ]:
#rand()
#used to create a random float value between 0 and 1
x=random.rand()
print(x)

0.13865631010116275


In [ ]:
x = random.rand(3,3)
print (x)

[[0.28718051 0.08437    0.84353177]
 [0.47776767 0.87257116 0.68570385]
 [0.99838773 0.0677119  0.75189369]]


In [ ]:
x = random.rand(3)
print (x)

[0.09187829 0.00311727 0.95336682]


In [ ]:
#numpy Broadcasting :
arr1 = np.array([1,2,3])
arr2 =np.array([4,5,6])#have same dimension for arr1 and arr2
print (arr1+arr2)
print (arr1*arr2)

[5 7 9]
[ 4 10 18]


In [ ]:
arr1 = np.array([1,2,3])
arr2 =np.array([4,5])
print (arr1+arr2)
print (arr1*arr2)
#here arr2 have 2 elemnt and arr1 has 3 so they have different dimension

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [ ]:
arr1 = np.array([1,2,3])
arr2 =np.array([4])
print (arr1+arr2)
print (arr1*arr2)
#term broadcast is valid for the any dimension with its ones elemnt from another array .

[5 6 7]
[ 4  8 12]
