<a href="https://colab.research.google.com/github/mayurraj9378/Data-Science/blob/main/numpy_part4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
#where()-->returns index numbers in an output
arr=np.array([8,94,8,56,1,3,4,5,7])
print(arr)
x=np.where(arr>5)
print(x)
print(arr[x])
print(x)


[ 8 94  8 56  1  3  4  5  7]
(array([0, 1, 2, 3, 8]),)
[ 8 94  8 56  7]
(array([0, 1, 2, 3, 8]),)


In [ ]:
#concatenate()
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [ ]:
arr2=np.array([[1,2],[3,4]])
arr3=np.array([[5,6],[7,8]])
arr=np.concatenate((arr2,arr3),axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12],[13,14,15]])
arr =np.concatenate((arr1,arr2))
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [ ]:
#split
#array_split(arrayName,splitValue)
arr1=np.array([3,4,5,6,7,8,9,10,3,4,5,6])
newarr=np.array_split(arr1,3)
print(newarr)
print(arr1.shape)
newarr=np.array_split(arr1,4)
print(newarr)

[array([3, 4, 5, 6]), array([ 7,  8,  9, 10]), array([3, 4, 5, 6])]
(12,)
[array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10,  3]), array([4, 5, 6])]


In [ ]:
#sorting of array
arr = np.array([1,4,2,7,9,3,5,8,6,10])
print(arr)
print(np.sort(arr))#by default it will sort in ascending order
print(np.sort(arr)[::-1])#by default it will sort in decending order

[ 1  4  2  7  9  3  5  8  6 10]
[ 1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1]


In [ ]:
#zeros()
#it is used to create an array filled with zeros
#by default data type will be float
arr=np.zeros(4)
print(arr)
x=np.zeros(7)
print(x)

[0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0.]


In [ ]:
x=np.zeros((3,3),dtype='i')
print(x)
#here the . dots are removed as it is integer

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
x=np.zeros((3,3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#ones()
#it is used to create an array filled with ones
#by default data type will be float
x=np.ones(7)
print(x)

[1. 1. 1. 1. 1. 1. 1.]


In [ ]:
x=np.ones(7,dtype='i')
print(x)

[1 1 1 1 1 1 1]
